#!/bin/sh

. /lib/functions.sh
. /usr/share/libubox/jshn.sh

log() {
        logger -s -t olsrwatchdog "$@"
}

[ -f "/var/run/olsrd.pid" -o -f "/var/run/olsrd6.pid" ] || {
	log "olsrd not running"
	return
}

run_watchdog() {
	local cfg="$1"
	config_get library "$cfg" library
	case "$library" in
		*watchdog* )
			config_get ignore "$cfg" ignore
			[ "$ignore" -eq "1" ] && {
				return
			}
			config_get interval "$cfg" interval
			config_get file "$cfg" file
			local last_olsr_stamp="$(cat $file)"
			local current_timestamp="$(date +'%s')"
			local diff=$(( $current_timestamp - $last_olsr_stamp ))
			if [ -z "$last_olsr_stamp" ] || [ "$diff" -ge "$(( $interval * 2 ))" ]; then
				log "OLSRd process died - restarting!"
			fi
		;;
		*)
			return
		;;
	esac
}
config_load olsrd
config_foreach run_watchdog LoadPlugin

