# Copyright (C) 2011 Manuel Munz <freifunk at somakoma de>
# Copyright (c) 2021 Sven Roederer <freifunk@it-solutions.geroedel.de>
# This is free software, licensed under the Apache 2.0 license.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Community profiles
LUCI_DEPENDS:=freifunk-common
LUCI_DESCRIPTION:=These community profiles set defaults for various free network/freifunk communities\
  and are used by wizards like ffwizard and meshwizard.

include ../../../freifunk.mk

# call BuildPackage - OpenWrt buildroot signature